// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Identifier struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identifier) Reset()         { *m = Identifier{} }
func (m *Identifier) String() string { return proto.CompactTextString(m) }
func (*Identifier) ProtoMessage()    {}
func (*Identifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Identifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identifier.Unmarshal(m, b)
}
func (m *Identifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identifier.Marshal(b, m, deterministic)
}
func (m *Identifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identifier.Merge(m, src)
}
func (m *Identifier) XXX_Size() int {
	return xxx_messageInfo_Identifier.Size(m)
}
func (m *Identifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Identifier.DiscardUnknown(m)
}

var xxx_messageInfo_Identifier proto.InternalMessageInfo

func (m *Identifier) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Document struct {
	Identifier           *Identifier `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Content              string      `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetIdentifier() *Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *Document) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type DocumentStoreReuest struct {
	Document             *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DocumentStoreReuest) Reset()         { *m = DocumentStoreReuest{} }
func (m *DocumentStoreReuest) String() string { return proto.CompactTextString(m) }
func (*DocumentStoreReuest) ProtoMessage()    {}
func (*DocumentStoreReuest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *DocumentStoreReuest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentStoreReuest.Unmarshal(m, b)
}
func (m *DocumentStoreReuest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentStoreReuest.Marshal(b, m, deterministic)
}
func (m *DocumentStoreReuest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentStoreReuest.Merge(m, src)
}
func (m *DocumentStoreReuest) XXX_Size() int {
	return xxx_messageInfo_DocumentStoreReuest.Size(m)
}
func (m *DocumentStoreReuest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentStoreReuest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentStoreReuest proto.InternalMessageInfo

func (m *DocumentStoreReuest) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type DocumentStoreResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentStoreResponse) Reset()         { *m = DocumentStoreResponse{} }
func (m *DocumentStoreResponse) String() string { return proto.CompactTextString(m) }
func (*DocumentStoreResponse) ProtoMessage()    {}
func (*DocumentStoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *DocumentStoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentStoreResponse.Unmarshal(m, b)
}
func (m *DocumentStoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentStoreResponse.Marshal(b, m, deterministic)
}
func (m *DocumentStoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentStoreResponse.Merge(m, src)
}
func (m *DocumentStoreResponse) XXX_Size() int {
	return xxx_messageInfo_DocumentStoreResponse.Size(m)
}
func (m *DocumentStoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentStoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentStoreResponse proto.InternalMessageInfo

type DocumentGetReuest struct {
	Identifier           *Identifier `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DocumentGetReuest) Reset()         { *m = DocumentGetReuest{} }
func (m *DocumentGetReuest) String() string { return proto.CompactTextString(m) }
func (*DocumentGetReuest) ProtoMessage()    {}
func (*DocumentGetReuest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *DocumentGetReuest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentGetReuest.Unmarshal(m, b)
}
func (m *DocumentGetReuest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentGetReuest.Marshal(b, m, deterministic)
}
func (m *DocumentGetReuest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentGetReuest.Merge(m, src)
}
func (m *DocumentGetReuest) XXX_Size() int {
	return xxx_messageInfo_DocumentGetReuest.Size(m)
}
func (m *DocumentGetReuest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentGetReuest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentGetReuest proto.InternalMessageInfo

func (m *DocumentGetReuest) GetIdentifier() *Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

type DocumentGetResponse struct {
	Document             *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DocumentGetResponse) Reset()         { *m = DocumentGetResponse{} }
func (m *DocumentGetResponse) String() string { return proto.CompactTextString(m) }
func (*DocumentGetResponse) ProtoMessage()    {}
func (*DocumentGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *DocumentGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentGetResponse.Unmarshal(m, b)
}
func (m *DocumentGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentGetResponse.Marshal(b, m, deterministic)
}
func (m *DocumentGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentGetResponse.Merge(m, src)
}
func (m *DocumentGetResponse) XXX_Size() int {
	return xxx_messageInfo_DocumentGetResponse.Size(m)
}
func (m *DocumentGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentGetResponse proto.InternalMessageInfo

func (m *DocumentGetResponse) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

func init() {
	proto.RegisterType((*Identifier)(nil), "service.Identifier")
	proto.RegisterType((*Error)(nil), "service.Error")
	proto.RegisterType((*Document)(nil), "service.Document")
	proto.RegisterType((*DocumentStoreReuest)(nil), "service.DocumentStoreReuest")
	proto.RegisterType((*DocumentStoreResponse)(nil), "service.DocumentStoreResponse")
	proto.RegisterType((*DocumentGetReuest)(nil), "service.DocumentGetReuest")
	proto.RegisterType((*DocumentGetResponse)(nil), "service.DocumentGetResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xbf, 0x4b, 0xc3, 0x40,
	0x14, 0xa6, 0x6a, 0x6c, 0xfd, 0x4a, 0x87, 0x5e, 0x15, 0x43, 0x28, 0x22, 0x37, 0xb9, 0xd8, 0x21,
	0xc5, 0xd9, 0xa5, 0x45, 0x5d, 0x1c, 0x4e, 0x10, 0x1c, 0x6b, 0xf2, 0x94, 0x80, 0xbd, 0x2b, 0x77,
	0x97, 0xfe, 0xfd, 0xd2, 0xfb, 0x11, 0xa3, 0xd1, 0xc1, 0x4e, 0x79, 0x5f, 0xbe, 0xf7, 0xfd, 0xc8,
	0x23, 0x18, 0x19, 0xd2, 0xdb, 0xaa, 0xa0, 0xd9, 0x46, 0x2b, 0xab, 0x58, 0x3f, 0x40, 0xce, 0x81,
	0x87, 0x92, 0xa4, 0xad, 0xde, 0x2a, 0xd2, 0xec, 0x14, 0xc9, 0x76, 0xf5, 0x51, 0x53, 0xda, 0xbb,
	0xec, 0x5d, 0x9d, 0x08, 0x0f, 0xf8, 0x0d, 0x92, 0xa5, 0xd6, 0x4a, 0x33, 0x86, 0xa3, 0x42, 0x95,
	0x9e, 0x4d, 0x84, 0x9b, 0x59, 0x8a, 0xfe, 0x9a, 0x8c, 0x59, 0xbd, 0x53, 0x7a, 0xe0, 0x44, 0x11,
	0xf2, 0x17, 0x0c, 0x16, 0xaa, 0xa8, 0xd7, 0x24, 0x2d, 0x9b, 0x03, 0x55, 0x13, 0xe3, 0xf4, 0xc3,
	0x7c, 0x32, 0x8b, 0x9d, 0xbe, 0x1a, 0x88, 0xd6, 0xda, 0xce, 0xba, 0x50, 0xd2, 0x92, 0xb4, 0xd1,
	0x3a, 0x40, 0xbe, 0xc0, 0x24, 0x5a, 0x3f, 0x59, 0xa5, 0x49, 0x50, 0x4d, 0xc6, 0xb2, 0x6b, 0x0c,
	0xca, 0xf0, 0x3a, 0x64, 0x8c, 0x9b, 0x8c, 0xb8, 0x2f, 0x9a, 0x15, 0x7e, 0x8e, 0xb3, 0x1f, 0x2e,
	0x66, 0xa3, 0xa4, 0x21, 0x7e, 0x8f, 0x71, 0x24, 0xee, 0xc8, 0x06, 0xf3, 0x7d, 0x3e, 0xa1, 0x5d,
	0xd4, 0x39, 0xf9, 0x80, 0x7f, 0x16, 0xcd, 0x9f, 0x31, 0xfa, 0x56, 0x94, 0x2d, 0x91, 0xf8, 0x61,
	0xda, 0x91, 0xb5, 0xee, 0x91, 0x5d, 0xfc, 0xc5, 0xfa, 0x1a, 0xf9, 0x23, 0x86, 0xad, 0x76, 0xec,
	0x16, 0x87, 0xbb, 0x47, 0xd6, 0x51, 0x35, 0x47, 0xc8, 0xa6, 0xbf, 0x73, 0xde, 0xef, 0xf5, 0xd8,
	0xfd, 0x5c, 0xf3, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0xba, 0x1d, 0x60, 0x6d, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DocumentStoreClient is the client API for DocumentStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DocumentStoreClient interface {
	Store(ctx context.Context, in *DocumentStoreReuest, opts ...grpc.CallOption) (*DocumentStoreResponse, error)
}

type documentStoreClient struct {
	cc *grpc.ClientConn
}

func NewDocumentStoreClient(cc *grpc.ClientConn) DocumentStoreClient {
	return &documentStoreClient{cc}
}

func (c *documentStoreClient) Store(ctx context.Context, in *DocumentStoreReuest, opts ...grpc.CallOption) (*DocumentStoreResponse, error) {
	out := new(DocumentStoreResponse)
	err := c.cc.Invoke(ctx, "/service.DocumentStore/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentStoreServer is the server API for DocumentStore service.
type DocumentStoreServer interface {
	Store(context.Context, *DocumentStoreReuest) (*DocumentStoreResponse, error)
}

// UnimplementedDocumentStoreServer can be embedded to have forward compatible implementations.
type UnimplementedDocumentStoreServer struct {
}

func (*UnimplementedDocumentStoreServer) Store(ctx context.Context, req *DocumentStoreReuest) (*DocumentStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}

func RegisterDocumentStoreServer(s *grpc.Server, srv DocumentStoreServer) {
	s.RegisterService(&_DocumentStore_serviceDesc, srv)
}

func _DocumentStore_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentStoreReuest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.DocumentStore/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Store(ctx, req.(*DocumentStoreReuest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DocumentStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.DocumentStore",
	HandlerType: (*DocumentStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _DocumentStore_Store_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// DocumentGetClient is the client API for DocumentGet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DocumentGetClient interface {
	Get(ctx context.Context, in *DocumentGetReuest, opts ...grpc.CallOption) (*DocumentGetResponse, error)
}

type documentGetClient struct {
	cc *grpc.ClientConn
}

func NewDocumentGetClient(cc *grpc.ClientConn) DocumentGetClient {
	return &documentGetClient{cc}
}

func (c *documentGetClient) Get(ctx context.Context, in *DocumentGetReuest, opts ...grpc.CallOption) (*DocumentGetResponse, error) {
	out := new(DocumentGetResponse)
	err := c.cc.Invoke(ctx, "/service.DocumentGet/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentGetServer is the server API for DocumentGet service.
type DocumentGetServer interface {
	Get(context.Context, *DocumentGetReuest) (*DocumentGetResponse, error)
}

// UnimplementedDocumentGetServer can be embedded to have forward compatible implementations.
type UnimplementedDocumentGetServer struct {
}

func (*UnimplementedDocumentGetServer) Get(ctx context.Context, req *DocumentGetReuest) (*DocumentGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterDocumentGetServer(s *grpc.Server, srv DocumentGetServer) {
	s.RegisterService(&_DocumentGet_serviceDesc, srv)
}

func _DocumentGet_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentGetReuest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentGetServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.DocumentGet/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentGetServer).Get(ctx, req.(*DocumentGetReuest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DocumentGet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.DocumentGet",
	HandlerType: (*DocumentGetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _DocumentGet_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
