// Code generated by protoc-gen-go. DO NOT EDIT.
// source: documents.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_37d3647adf041676, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Identifier struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identifier) Reset()         { *m = Identifier{} }
func (m *Identifier) String() string { return proto.CompactTextString(m) }
func (*Identifier) ProtoMessage()    {}
func (*Identifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_37d3647adf041676, []int{1}
}

func (m *Identifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identifier.Unmarshal(m, b)
}
func (m *Identifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identifier.Marshal(b, m, deterministic)
}
func (m *Identifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identifier.Merge(m, src)
}
func (m *Identifier) XXX_Size() int {
	return xxx_messageInfo_Identifier.Size(m)
}
func (m *Identifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Identifier.DiscardUnknown(m)
}

var xxx_messageInfo_Identifier proto.InternalMessageInfo

func (m *Identifier) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Document struct {
	Identifier           *Identifier `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Content              string      `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_37d3647adf041676, []int{2}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetIdentifier() *Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *Document) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type DocumentStoreReuest struct {
	Document             *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DocumentStoreReuest) Reset()         { *m = DocumentStoreReuest{} }
func (m *DocumentStoreReuest) String() string { return proto.CompactTextString(m) }
func (*DocumentStoreReuest) ProtoMessage()    {}
func (*DocumentStoreReuest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37d3647adf041676, []int{3}
}

func (m *DocumentStoreReuest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentStoreReuest.Unmarshal(m, b)
}
func (m *DocumentStoreReuest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentStoreReuest.Marshal(b, m, deterministic)
}
func (m *DocumentStoreReuest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentStoreReuest.Merge(m, src)
}
func (m *DocumentStoreReuest) XXX_Size() int {
	return xxx_messageInfo_DocumentStoreReuest.Size(m)
}
func (m *DocumentStoreReuest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentStoreReuest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentStoreReuest proto.InternalMessageInfo

func (m *DocumentStoreReuest) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type DocumentGetReuest struct {
	Identifier           *Identifier `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DocumentGetReuest) Reset()         { *m = DocumentGetReuest{} }
func (m *DocumentGetReuest) String() string { return proto.CompactTextString(m) }
func (*DocumentGetReuest) ProtoMessage()    {}
func (*DocumentGetReuest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37d3647adf041676, []int{4}
}

func (m *DocumentGetReuest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentGetReuest.Unmarshal(m, b)
}
func (m *DocumentGetReuest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentGetReuest.Marshal(b, m, deterministic)
}
func (m *DocumentGetReuest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentGetReuest.Merge(m, src)
}
func (m *DocumentGetReuest) XXX_Size() int {
	return xxx_messageInfo_DocumentGetReuest.Size(m)
}
func (m *DocumentGetReuest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentGetReuest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentGetReuest proto.InternalMessageInfo

func (m *DocumentGetReuest) GetIdentifier() *Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

type DocumentGetResponse struct {
	Document             *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DocumentGetResponse) Reset()         { *m = DocumentGetResponse{} }
func (m *DocumentGetResponse) String() string { return proto.CompactTextString(m) }
func (*DocumentGetResponse) ProtoMessage()    {}
func (*DocumentGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37d3647adf041676, []int{5}
}

func (m *DocumentGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentGetResponse.Unmarshal(m, b)
}
func (m *DocumentGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentGetResponse.Marshal(b, m, deterministic)
}
func (m *DocumentGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentGetResponse.Merge(m, src)
}
func (m *DocumentGetResponse) XXX_Size() int {
	return xxx_messageInfo_DocumentGetResponse.Size(m)
}
func (m *DocumentGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentGetResponse proto.InternalMessageInfo

func (m *DocumentGetResponse) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "service.Empty")
	proto.RegisterType((*Identifier)(nil), "service.Identifier")
	proto.RegisterType((*Document)(nil), "service.Document")
	proto.RegisterType((*DocumentStoreReuest)(nil), "service.DocumentStoreReuest")
	proto.RegisterType((*DocumentGetReuest)(nil), "service.DocumentGetReuest")
	proto.RegisterType((*DocumentGetResponse)(nil), "service.DocumentGetResponse")
}

func init() { proto.RegisterFile("documents.proto", fileDescriptor_37d3647adf041676) }

var fileDescriptor_37d3647adf041676 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0x89, 0x12, 0x73, 0x37, 0x82, 0x72, 0x73, 0x16, 0x21, 0x5c, 0x21, 0x5b, 0xd9, 0x98,
	0xe2, 0x0e, 0x6b, 0x9b, 0x93, 0xd3, 0x76, 0xad, 0x2c, 0x35, 0x37, 0xc2, 0x82, 0xd9, 0x0d, 0xbb,
	0x93, 0x80, 0xb5, 0x7f, 0x5c, 0xd8, 0xec, 0xae, 0x81, 0xd8, 0x68, 0x39, 0x33, 0x6f, 0xbe, 0x79,
	0x8f, 0x81, 0xcb, 0xa3, 0x69, 0xfa, 0x96, 0x34, 0xbb, 0xba, 0xb3, 0x86, 0x0d, 0x16, 0x8e, 0xec,
	0xa0, 0x1a, 0x12, 0x05, 0xe4, 0x0f, 0x6d, 0xc7, 0x9f, 0x42, 0x00, 0x3c, 0x1d, 0x49, 0xb3, 0x7a,
	0x57, 0x64, 0xf1, 0x0a, 0xf2, 0xe1, 0xf5, 0xa3, 0xa7, 0x32, 0xbb, 0xce, 0x6e, 0x96, 0x72, 0x2c,
	0xc4, 0x0b, 0x2c, 0xf6, 0x01, 0x84, 0x3b, 0x00, 0x95, 0xf4, 0x5e, 0x76, 0xbe, 0x5d, 0xd7, 0x01,
	0x5b, 0xff, 0xa0, 0xe4, 0x44, 0x86, 0x25, 0x14, 0x8d, 0xd1, 0x4c, 0x9a, 0xcb, 0x13, 0x0f, 0x8e,
	0xa5, 0xd8, 0xc3, 0x3a, 0xa2, 0x9f, 0xd9, 0x58, 0x92, 0xd4, 0x93, 0x63, 0xbc, 0x85, 0x45, 0xb4,
	0x1e, 0x6e, 0xac, 0xd2, 0x8d, 0xa8, 0x97, 0x49, 0x22, 0x1e, 0x61, 0x15, 0xbb, 0x07, 0xe2, 0xc0,
	0xf8, 0x8f, 0xd3, 0xa9, 0x1f, 0x4f, 0x72, 0x9d, 0xd1, 0x8e, 0xfe, 0xe8, 0x67, 0xfb, 0x95, 0xc1,
	0x32, 0xb6, 0x1d, 0xde, 0x41, 0xee, 0xb3, 0xe1, 0x66, 0xb6, 0x33, 0xc9, 0x5c, 0x5d, 0xa4, 0xa9,
	0xff, 0x0c, 0xde, 0xc3, 0xe9, 0x81, 0x18, 0xab, 0xd9, 0x52, 0x8a, 0x58, 0x6d, 0x7e, 0x9f, 0x8d,
	0xa6, 0xdf, 0xce, 0xfc, 0xcf, 0x77, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xa9, 0x4e, 0x08,
	0x06, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DocumentsClient is the client API for Documents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DocumentsClient interface {
	Store(ctx context.Context, in *DocumentStoreReuest, opts ...grpc.CallOption) (*Empty, error)
	Get(ctx context.Context, in *DocumentGetReuest, opts ...grpc.CallOption) (*DocumentGetResponse, error)
}

type documentsClient struct {
	cc *grpc.ClientConn
}

func NewDocumentsClient(cc *grpc.ClientConn) DocumentsClient {
	return &documentsClient{cc}
}

func (c *documentsClient) Store(ctx context.Context, in *DocumentStoreReuest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/service.Documents/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsClient) Get(ctx context.Context, in *DocumentGetReuest, opts ...grpc.CallOption) (*DocumentGetResponse, error) {
	out := new(DocumentGetResponse)
	err := c.cc.Invoke(ctx, "/service.Documents/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentsServer is the server API for Documents service.
type DocumentsServer interface {
	Store(context.Context, *DocumentStoreReuest) (*Empty, error)
	Get(context.Context, *DocumentGetReuest) (*DocumentGetResponse, error)
}

// UnimplementedDocumentsServer can be embedded to have forward compatible implementations.
type UnimplementedDocumentsServer struct {
}

func (*UnimplementedDocumentsServer) Store(ctx context.Context, req *DocumentStoreReuest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (*UnimplementedDocumentsServer) Get(ctx context.Context, req *DocumentGetReuest) (*DocumentGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterDocumentsServer(s *grpc.Server, srv DocumentsServer) {
	s.RegisterService(&_Documents_serviceDesc, srv)
}

func _Documents_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentStoreReuest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Documents/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).Store(ctx, req.(*DocumentStoreReuest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documents_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentGetReuest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Documents/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).Get(ctx, req.(*DocumentGetReuest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Documents_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Documents",
	HandlerType: (*DocumentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _Documents_Store_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Documents_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "documents.proto",
}
